/*
 * AVENTRIX REALTY — PROPERTIES MODULE
 * -------------------------------------------
 * Full CRUD for the `properties` table: list with filters, add/edit
 * modal with multi-image upload to Supabase Storage, draft/publish,
 * availability status, featured toggle, and SEO fields.
 *
 * property_code (the friendly unique ID, e.g. AVX-000123) and the
 * created/updated timestamps are generated by the database (see
 * sql/schema.sql) — this file never sets them directly.
 */

const PropertiesModule = (function () {
    const BUCKET = "property-images";
    let currentImages = [];        // existing gallery image URLs kept for the property being edited
    let newFiles = [];             // newly selected gallery File objects not yet uploaded
    let currentFeaturedImage = ""; // existing featured image URL (empty = none set)
    let newFeaturedFile = null;    // newly selected featured image File, not yet uploaded
    let editingId = null;

    const els = {};

    function cacheEls() {
        [
            "propertiesTableBody", "propertiesEmptyState", "filterPublishStatus", "filterStatus",
            "propertyModalOverlay", "propertyModalTitle", "propertyCodeDisplay", "propertyForm2",
            "fTitle", "fCategory", "fListingType", "fLocation", "fPrice", "fShortDesc", "fDescription",
            "fFeatures", "fFeaturedImage", "featuredImagePreview", "fImages", "imagePreviewList",
            "fBedrooms", "fBathrooms", "fParking", "fFloors", "fBuiltUpArea", "fLandArea", "fRoadWidth", "fRentalIncome", "fBrokerage",
            "fUdsArea", "fFurnishing", "fFacing",
            "fStatus", "fPublishStatus", "fFeatured",
            "fSeoTitle", "fSeoDescription", "fSeoKeywords",
            "uploadProgressWrap", "uploadProgressBar", "uploadProgressLabel"
        ].forEach((id) => (els[id] = document.getElementById(id)));
    }

    function slugify(title) {
        return title.toLowerCase().trim()
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/(^-|-$)/g, "") + "-" + Math.random().toString(36).slice(2, 6);
    }

    function statusBadgeClass(status) {
        return { "Available": "badge-available", "Sold": "badge-sold", "Under Negotiation": "badge-negotiation", "Rented": "badge-rented" }[status] || "";
    }

    async function load() {
        const filters = {
            publish_status: els.filterPublishStatus.value,
            status: els.filterStatus.value
        };
        const rows = await CrudEngine.list("properties", { filters });
        renderTable(rows);
    }

    function renderTable(rows) {
        els.propertiesEmptyState.style.display = rows.length ? "none" : "block";
        els.propertiesTableBody.innerHTML = rows.map((p) => `
            <tr>
                <td><img class="thumb" src="${p.featured_image || (p.images && p.images[0]) || 'https://placehold.co/80x80?text=No+Image'}" alt=""></td>
                <td><strong>${escapeHtml(p.title)}</strong><br><span class="helper-text">${escapeHtml(p.location || "")}</span></td>
                <td><span class="code-pill">${escapeHtml(p.property_code || "—")}</span></td>
                <td><span class="badge ${statusBadgeClass(p.status)}">${escapeHtml(p.status)}</span></td>
                <td><span class="badge ${p.publish_status === "Published" ? "badge-published" : "badge-draft"}">${escapeHtml(p.publish_status)}</span></td>
                <td>${p.is_featured ? '<span class="badge badge-featured">Featured</span>' : "—"}</td>
                <td><span class="helper-text">${p.updated_at ? new Date(p.updated_at).toLocaleDateString() : "—"}</span></td>
                <td class="admin-actions-cell">
                    <button class="icon-btn" title="Edit" onclick="PropertiesModule.openEdit('${p.id}')"><i class="fas fa-pen"></i></button>
                    <button class="icon-btn danger" title="Delete" onclick="PropertiesModule.remove('${p.id}')"><i class="fas fa-trash"></i></button>
                </td>
            </tr>
        `).join("");
    }

    function escapeHtml(str) {
        return String(str || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
    }

    function resetForm() {
        editingId = null;
        currentImages = [];
        newFiles = [];
        currentFeaturedImage = "";
        newFeaturedFile = null;
        els.propertyForm2.reset();
        els.propertyCodeDisplay.style.display = "none";
        els.propertyModalTitle.textContent = "Add Property";
        hideProgress();
        renderImagePreviews();
        renderFeaturedPreview();
    }

    function openAdd() {
        resetForm();
        els.propertyModalOverlay.classList.add("open");
    }

    async function openEdit(id) {
        resetForm();
        const p = await CrudEngine.getOne("properties", id);
        editingId = id;
        currentImages = p.images || [];
        currentFeaturedImage = p.featured_image || "";

        els.propertyModalTitle.textContent = "Edit Property";
        els.propertyCodeDisplay.textContent = "Property ID: " + (p.property_code || "—") +
            " · Created " + new Date(p.created_at).toLocaleDateString() +
            " · Updated " + new Date(p.updated_at).toLocaleDateString();
        els.propertyCodeDisplay.style.display = "block";

        els.fTitle.value = p.title || "";
        els.fCategory.value = p.category || "residential";
        els.fListingType.value = p.listing_type || "sale";
        els.fLocation.value = p.location || "";
        els.fPrice.value = p.price_display || "";
        els.fShortDesc.value = p.short_description || "";
        els.fDescription.value = p.description || "";
        els.fFeatures.value = (p.features || []).join("\n");
        els.fBedrooms.value = p.bedrooms ?? "";
        els.fBathrooms.value = p.bathrooms ?? "";
        els.fParking.value = p.parking ?? "";
        els.fFloors.value = p.floors ?? "";
        els.fBuiltUpArea.value = p.built_up_area || "";
        els.fLandArea.value = p.land_area || "";
        els.fRoadWidth.value = p.road_width || "";
        els.fRentalIncome.value = p.rental_income || "";
        els.fBrokerage.value = p.brokerage || "";
        els.fUdsArea.value = p.uds_area || "";
        els.fFurnishing.value = p.furnishing || "";
        els.fFacing.value = p.facing || "";
        els.fStatus.value = p.status || "Available";
        els.fPublishStatus.value = p.publish_status || "Draft";
        els.fFeatured.checked = !!p.is_featured;
        els.fSeoTitle.value = p.seo_title || "";
        els.fSeoDescription.value = p.seo_description || "";
        els.fSeoKeywords.value = p.seo_keywords || "";

        renderImagePreviews();
        renderFeaturedPreview();
        els.propertyModalOverlay.classList.add("open");
    }

    function closeModal() {
        els.propertyModalOverlay.classList.remove("open");
    }

    // ---- Gallery images (multiple) ----

    function renderImagePreviews() {
        const existing = currentImages.map((url, i) => `
            <div class="thumb-wrap">
                <img src="${url}" alt="">
                <button type="button" class="remove-thumb" onclick="PropertiesModule.removeExistingImage(${i})">&times;</button>
            </div>`).join("");
        const pending = newFiles.map((file, i) => `
            <div class="thumb-wrap">
                <img src="${URL.createObjectURL(file)}" alt="">
                <button type="button" class="remove-thumb" onclick="PropertiesModule.removeNewFile(${i})">&times;</button>
            </div>`).join("");
        els.imagePreviewList.innerHTML = existing + pending;
    }

    function removeExistingImage(index) {
        currentImages.splice(index, 1);
        renderImagePreviews();
    }

    function removeNewFile(index) {
        newFiles.splice(index, 1);
        renderImagePreviews();
    }

    function handleFileSelect(e) {
        const files = Array.from(e.target.files);
        const rejected = files.filter((f) => !CrudEngine.isAllowedImage(f));
        const accepted = files.filter((f) => CrudEngine.isAllowedImage(f));
        if (rejected.length) {
            showToast(`Skipped ${rejected.length} file(s) — only JPG, JPEG, PNG or WEBP are supported.`, true);
        }
        newFiles = newFiles.concat(accepted);
        e.target.value = "";
        renderImagePreviews();
    }

    // ---- Featured image (single) ----

    function renderFeaturedPreview() {
        if (newFeaturedFile) {
            els.featuredImagePreview.innerHTML = `
                <div class="thumb-wrap featured-thumb-wrap">
                    <img src="${URL.createObjectURL(newFeaturedFile)}" alt="">
                    <button type="button" class="remove-thumb" onclick="PropertiesModule.removeFeaturedImage()">&times;</button>
                </div>`;
        } else if (currentFeaturedImage) {
            els.featuredImagePreview.innerHTML = `
                <div class="thumb-wrap featured-thumb-wrap">
                    <img src="${currentFeaturedImage}" alt="">
                    <button type="button" class="remove-thumb" onclick="PropertiesModule.removeFeaturedImage()">&times;</button>
                </div>`;
        } else {
            els.featuredImagePreview.innerHTML = `<p class="helper-text" style="margin:8px 0 0;">No featured image set — the first gallery image will be used on the website until one is uploaded here.</p>`;
        }
    }

    function removeFeaturedImage() {
        newFeaturedFile = null;
        currentFeaturedImage = "";
        renderFeaturedPreview();
    }

    function handleFeaturedFileSelect(e) {
        const file = e.target.files[0];
        e.target.value = "";
        if (!file) return;
        if (!CrudEngine.isAllowedImage(file)) {
            showToast("Only JPG, JPEG, PNG or WEBP images are supported.", true);
            return;
        }
        newFeaturedFile = file; // replaces any existing featured image
        renderFeaturedPreview();
    }

    // ---- Upload progress bar ----

    function showProgress(label) {
        els.uploadProgressWrap.style.display = "block";
        els.uploadProgressBar.style.width = "0%";
        els.uploadProgressLabel.textContent = label;
    }

    function updateProgress({ done, total, percent, fileName }) {
        els.uploadProgressBar.style.width = percent + "%";
        els.uploadProgressLabel.textContent = `Uploading image ${done} of ${total} (${fileName})…`;
    }

    function hideProgress() {
        els.uploadProgressWrap.style.display = "none";
        els.uploadProgressBar.style.width = "0%";
    }

    async function remove(id) {
        if (!confirm("Delete this property? This can't be undone.")) return;
        try {
            await CrudEngine.remove("properties", id);
            showToast("Property deleted");
            load();
        } catch (err) {
            showToast("Delete failed: " + err.message, true);
        }
    }

    async function handleSubmit(e) {
        e.preventDefault();
        const btn = document.getElementById("savePropertyBtn");
        btn.disabled = true;
        btn.textContent = "Saving...";

        try {
            const totalUploads = newFiles.length + (newFeaturedFile ? 1 : 0);
            let uploadedUrls = [];
            let featuredUrl = currentFeaturedImage;

            if (totalUploads) {
                showProgress(`Uploading ${totalUploads} image${totalUploads > 1 ? "s" : ""}…`);
                let uploadedSoFar = 0;

                if (newFeaturedFile) {
                    featuredUrl = await CrudEngine.uploadImage(BUCKET, newFeaturedFile, "properties/featured");
                    uploadedSoFar += 1;
                    updateProgress({ done: uploadedSoFar, total: totalUploads, percent: Math.round((uploadedSoFar / totalUploads) * 100), fileName: newFeaturedFile.name });
                }

                if (newFiles.length) {
                    uploadedUrls = await CrudEngine.uploadImagesWithProgress(BUCKET, newFiles, "properties", (p) => {
                        updateProgress({
                            done: uploadedSoFar + p.done,
                            total: totalUploads,
                            percent: Math.round(((uploadedSoFar + p.done) / totalUploads) * 100),
                            fileName: p.fileName
                        });
                    });
                }
            }

            const images = currentImages.concat(uploadedUrls);

            const record = {
                title: els.fTitle.value.trim(),
                category: els.fCategory.value,
                listing_type: els.fListingType.value,
                location: els.fLocation.value.trim(),
                price_display: els.fPrice.value.trim(),
                short_description: els.fShortDesc.value.trim(),
                description: els.fDescription.value.trim(),
                features: els.fFeatures.value.split("\n").map((s) => s.trim()).filter(Boolean),
                bedrooms: els.fBedrooms.value ? parseInt(els.fBedrooms.value, 10) : null,
                bathrooms: els.fBathrooms.value ? parseInt(els.fBathrooms.value, 10) : null,
                parking: els.fParking.value ? parseInt(els.fParking.value, 10) : null,
                floors: els.fFloors.value ? parseInt(els.fFloors.value, 10) : null,
                built_up_area: els.fBuiltUpArea.value.trim(),
                land_area: els.fLandArea.value.trim(),
                road_width: els.fRoadWidth.value.trim(),
                rental_income: els.fRentalIncome.value.trim(),
                brokerage: els.fBrokerage.value.trim(),
                uds_area: els.fUdsArea.value.trim(),
                furnishing: els.fFurnishing.value,
                facing: els.fFacing.value,
                featured_image: featuredUrl || "",
                images: images,
                status: els.fStatus.value,
                publish_status: els.fPublishStatus.value,
                is_featured: els.fFeatured.checked,
                seo_title: els.fSeoTitle.value.trim(),
                seo_description: els.fSeoDescription.value.trim(),
                seo_keywords: els.fSeoKeywords.value.trim()
            };

            if (editingId) {
                await CrudEngine.update("properties", editingId, record);
                showToast("Property updated");
            } else {
                record.slug = slugify(record.title || "property");
                await CrudEngine.insert("properties", record);
                showToast("Property created");
            }

            closeModal();
            load();
        } catch (err) {
            console.error(err);
            showToast("Save failed: " + err.message, true);
        } finally {
            btn.disabled = false;
            btn.textContent = "Save Property";
            hideProgress();
        }
    }

    function bindEvents() {
        document.getElementById("addPropertyBtn").addEventListener("click", openAdd);
        document.getElementById("closePropertyModal").addEventListener("click", closeModal);
        document.getElementById("cancelPropertyBtn").addEventListener("click", closeModal);
        els.propertyForm2.addEventListener("submit", handleSubmit);
        els.fImages.addEventListener("change", handleFileSelect);
        els.fFeaturedImage.addEventListener("change", handleFeaturedFileSelect);
        els.filterPublishStatus.addEventListener("change", load);
        els.filterStatus.addEventListener("change", load);
    }

    document.addEventListener("DOMContentLoaded", () => {
        cacheEls();
        bindEvents();
    });

    return { load, openEdit, remove, removeExistingImage, removeNewFile, removeFeaturedImage };
})();

window.PropertiesModule = PropertiesModule;
